### DISCUSSION TITLE
env(safe-area-inset-*) not working

### DISCUSSION THREAD

**Discussion by marcelxpfeifer** [ionic-team/capacitor#6688] [Q&A] [answered]
Inside the browser in capacitor the env(safe-area-inset-*) is set to 0px. Even if the device has a safe area.
I know in older capacitor versions this used to work. Are the some workarounds in place? Should I open up an issue?

The styling:
```css
 body {
        background-color: red;
}
.content {
        margin-top: env(safe-area-inset-top);
        margin-bottom: env(safe-area-inset-bottom);
        height: 100%;
        background-color: white;
        font-size: 60px;
        color: black;
        display: flex;
        align-items: center;
        justify-content: center;
}
``` 

The result:
<img width="565" alt="image" src="https://github.com/ionic-team/capacitor/assets/40826752/62ad5172-330e-417e-83cd-f73b227b4656">
