### ISSUE TITLE
bug: Keyboard doesn't hide outside inputs and textarea is not working

### ISSUE THREAD

**Issue by htorbov** [ionic-team/capacitor#2299]
## Versions
Vue + Bootstrap + Capacitor (latest versions)

## Platforms
I've tested on iOS only

## Behavior
Clicking on `input` fires `keyboard.show`, but clicking outside doesn't fire `keyboard.hide`. Typing in `textarea` does nothing. Also, `keyboard.show` looks buggy (adds black background).

---

**Temporary fix for keyboard not hiding**
```ts
window.addEventListener('touchend', (response) => {
  if (response.target && response.target.nodeName !== 'INPUT' && response.target.nodeName !== 'SELECT' && response.target.nodeName !== 'TEXTAREA') {
    this.$Plugins.Keyboard.hide()
  }
})
```

**Temporary fix for textarea issue**
```css
textarea {
  -webkit-user-select: text;
  -khtml-user-select: text;
  -moz-user-select: text;
  -ms-user-select: text;
  user-select: text;
}
```
