### ISSUE TITLE
bug: unextended-module-overlay.yaml generated as invalid file

### ISSUE THREAD

**Issue by craftedsystems** [ionic-team/capacitor#5202]
### Capacitor Version

```
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 3.3.0
  @capacitor/core: 3.3.0
  @capacitor/android: 3.3.0
  @capacitor/ios: 3.3.0

Installed Dependencies:

  @capacitor/cli: 3.3.0
  @capacitor/core: 3.3.0
  @capacitor/android: 3.3.0
  @capacitor/ios: 3.3.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)

* iOS

### Current Behavior

* generated `unextended-module-overlay.yaml` file is a JSON with a missing `,` — not a YAML as its extension

```yaml
{
  'version': 0,
  'case-sensitive': 'false',
  'roots': [{
    'type': 'directory',
    'name': "/Users/[removed-path]/ios/DerivedData/77BA122C-41F0-457D-B22A-AC25BF19B52D/Build/Products/Debug-iphonesimulator/Capacitor/Capacitor.framework/Modules"
    'contents': [{
      'type': 'file',
      'name': "module.modulemap",
      'external-contents': "/Users/[removed-path]/ios/DerivedData/77BA122C-41F0-457D-B22A-AC25BF19B52D/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/Capacitor.build/unextended-module.modulemap",
    }]
  }]
}
```

### Expected Behavior

* should be a valid YAML (or a valid JSON with correct extension)
