### ISSUE TITLE
feat: Update the GitHub action setup-java from adopt to zulu of the OpenJDK.

### ISSUE THREAD

**Issue by carldea** [ionic-team/capacitor#5266]
## Feature Request
Not a feature but an update to the GitHub Actions setup-java to update the discontinued `adopt` build distribution of the OpenJDK.

### Description

The AdoptOpenJDK has been discontinued since July 2021 (https://adoptopenjdk.net). Switching the distribution to Azul Zulu. When using Zulu you get all the latest updated (TCK Tested) builds for all versions of OpenJDK. 

Please see more details at Foojay.io:
https://foojay.io/today/github-actions-with-java-part-2/

### Platform(s)

N/A

### Preferred Solution

```yaml
        uses: actions/setup-java@v2
         with:
           java-version: '11'
           distribution: 'zulu'
```

### Alternatives

distribution: 'temurin'

### Additional Context

https://adoptopenjdk.net/
https://foojay.io/today/github-actions-with-java-part-2/
