### ISSUE TITLE
bug: cannot build with bitbucket pipelines

### ISSUE THREAD

**Issue by franckysolo** [ionic-team/capacitor#5505]
## Bug Report

Hello,
i am trying to build debug android app with bitbucket pipelines but i am stuck with gradle build
it seems not find capacitor android dependencies
I am missing something?

### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.4.3
  @capacitor/core: 3.4.3
  @capacitor/android: 3.4.3
  @capacitor/ios: 3.4.3

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 3.4.3
  @capacitor/core: 3.4.3
  @capacitor/android: 3.4.3

[success] Android looking great! 👌
```

### Platform(s)
Linux

### Current Behavior

```
FAILURE: Build failed with an exception.
* What went wrong:
Could not determine the dependencies of task ':app:mergeDebugAssets'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve project :capacitor-android.
     Required by:
         project :app
```

### Expected Behavior

```
BUILD SUCCESSFUL
```

### Code Reproduction

```
image: node:lts

definitions:
  caches:
    yarn: $HOME/.cache

pipelines:
  custom:
    build-debug:
      - step:
          name: Build ionic app
          caches:
            - node
            - yarn
          script:
            - rm -rf android
            - yarn build
            - npx cap add android
            - npx cap sync
          artifacts:
            - android/**
      - step: 
          name: Build debug android app
          image: androidsdk/android-30
          caches:
            - gradle
          script:
            - cd android
            - ./gradlew assembleDebug
          artifacts:
            - app/build/outputs/**
```

### Other Technical Details

```

Ionic:

   Ionic CLI       : 6.18.1 
   Ionic Framework : @ionic/vue 6.0.11

Capacitor:

   Capacitor CLI      : 3.4.3
   @capacitor/android : 3.4.3
   @capacitor/core    : 3.4.3
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.5.0

System:

   NodeJS : v14.19.0 
   npm    : 6.14.8
   OS     : Linux 4.15
```

### Additional Context

Fresh Ionic 6 application
