### ISSUE TITLE
bug: Targeting R+ requires the `resources.arsc` of installed APKs to be stored uncompressed and aligned on a 4-byte boundary

### ISSUE THREAD

**Issue by NatoBoram** [ionic-team/capacitor#6794]
## Bug Report

It's not possible to install APKs generated from Capacitor.

```sh
pnpm build
cap sync android
cap build android --keystorepath keystore.jks --keystorepass hunter2 --keystorealias key --keystorealiaspass hunter2 --androidreleasetype APK
adb install -r -d android/app/build/outputs/apk/release/app-release-signed.apk
```

### Capacitor Version

```yaml
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.2.2
  @capacitor/core: 5.2.2
  @capacitor/android: 5.2.2
  @capacitor/ios: 5.2.2

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 5.2.2
  @capacitor/core: 5.2.2
  @capacitor/android: 5.2.2

[error] Missing <manifest package=""> attribute in app/src/main
```

### Platform(s)

* android

### Current Behavior

When using `jarsigner`:

```sh
Performing Streamed Install
adb: failed to install ./android/app/build/outputs/apk/release/app-release-signed.apk: Failure [-124: Failed parse during installPackageLI: Targeting R+ (version 30 and above) requires the resources.arsc of installed APKs to be stored uncompressed and aligned on a 4-byte boundary]
 ELIFECYCLE  Command failed with exit code 1.
```

When using `apksigner`:

```sh
Performing Streamed Install
adb: failed to install ./android/app/build/outputs/apk/release/app-release-signed.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Scanning Failed.: No signature found in package of version 2 or newer for package com.natoboram.leanish]
 ELIFECYCLE  Command failed with exit code 1.
```

### Expected Behavior

```sh
Performing Streamed Install
Success
```

### Code Reproduction

Soon™

### Other Technical Details

Host:
```yaml
OS: Pop!_OS 22.04 LTS x86_64 
Host: MS-7D53 1.0 
Kernel: 6.4.6-76060406-generic 
Shell: zsh 5.8.1 
CPU: AMD Ryzen 5 5600X (12) @ 3.700GHz 
GPU: AMD ATI Radeon RX 6700/6700 XT / 6800M 
Memory: 12704MiB / 32007MiB 
```

IDE:
```yaml
Version: 1.82.0-insider
Commit: 83fc3ad9bd553869e8fea3d370d1d2bd438f9e54
Date: 2023-08-04T05:34:49.736Z
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Code-Insiders/1.82.0-insider Chrome/108.0.5359.215 Electron/22.3.18 Safari/537.36
```

Phone:
```yaml
OS: Android 14 aarch64
Host: google Pixel 7 Pro
Kernel: 5.10.157-android13-4-00001-g5c7ff5dc7aac-ab10381520
Shell: zsh 5.9
CPU: (8) @ 1.803GHz
Memory: 6846MiB / 11454MiB
```

`pnpm --version` output:

8.6.12

`node --version` output:

v20.5.0

`pod --version` output (iOS issues only):

```sh
Command 'pod' not found, did you mean:
  command 'pom' from deb bsdgames (2.17-29)
  command 'pods' from deb pmtools (2.2.0-2)
  command 'wod' from deb sope-bin (5.5.1-1)
  command 'god' from deb ruby-god (0.13.7-3build3)
  command 'pwd' from deb coreutils (8.32-4.1ubuntu1)
  command 'pdd' from deb pdd (1.5-1)
  command 'pon' from deb ppp (2.4.9-1+1ubuntu3)
  command 'pd' from deb puredata-core (0.52.1+ds0-1)
  command 'od' from deb coreutils (8.32-4.1ubuntu1)
  command 'psd' from deb profile-sync-daemon (6.34-1)
  command 'poa' from deb poa (2.0+20060928-8)
  command 'mod' from deb monodoc-base (6.8.0.105+dfsg-3.2)
Try: sudo apt install <deb name>
```

### Additional Context

* #6714 was closed without a resolution
