### ISSUE TITLE
[Bug]: @capacitor-community/barcode-scanner does not show live-camera on Android, Web is ok

### ISSUE THREAD

**Issue by Jenziner** [ionic-team/capacitor#7645]
### Capacitor Version

6.1.2

### Other API Details

```Shell
cap: 6.1.2
npm: 10.8.1
node: 20.16.0
```

### Platforms Affected

- [ ] iOS
- [X] Android
- [X] Web

### Current Behavior

The functionality is ok, the scanner does its job. But the Cam-Image is not visible on the android-device during the scanning process. In the Web, the Cam is displayed correctly.

When I assume the position of a QRCode, the QRCode will be read and the content then perfectly handled. But I can't visually control the cam, because I do not see the "live image"...

### Expected Behavior

The live-cam preview should be visible as in Web.

### Project Reproduction

https://github.com/Jenziner/JEDO/tree/main/WALLET

### Additional Information

Code can be found here: https://github.com/Jenziner/JEDO/tree/main/WALLET (affected is the tab "tab_sending" - ../src/app/tab_sending/tab_sending.page.ts)

Tested on two devices, same behavior:
- Google Pixel 8 pro with Graphene OS
- Huawei P30 Lite with Google Android

**Comment by LennonReid** [comment]
Hi @Jenziner ,

It seems that you might have posted this issue in the wrong place. This repository is for the Ionic team, not the Capacitor Community. You should submit the issue here: https://github.com/capacitor-community/barcode-scanner/issues.

That being said, no worries! I might be able to help you resolve the problem you're encountering. I've experienced the same issue you're mentioning, and it is likely due to missing CSS. You can add the following code to your `global.scss` file:

```css
body.scanner-active {
  --background: transparent;
  // --ion-background-color: transparent;
  background: none transparent;

  ion-content {
    --background: transparent;
  }
}

.scanner-active {
  --background: transparent;
  background: none transparent;

  ion-content {
    --background: transparent;
  }
}
```

For a detailed explanation, please refer to the documentation: https://github.com/capacitor-community/barcode-scanner/blob/main/README.md.
